language: php

php:
  - 7.4
  - 8.0

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

install:
  - composer install

script:
  - vendor/bin/phpunit

  - >
    echo "Running php lint";
    find src tests -name \*.php | xargs -I % php -d display_errors=stderr -l % > /dev/null ;

  - vendor/bin/phpcs --runtime-set ignore_warnings_on_exit 1 --standard=vendor/vierwd/coding-standard/ForwardMedia src tests

  - vendor/bin/phpstan analyze
